env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - './.linters/tsconfig.json'
    - './tsconfig.json'

plugins:
  - jest
  - '@typescript-eslint'

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

rules:
  {
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-floating-promises': 'error',
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/no-null': 'off',
    'unicorn/prefer-top-level-await': 'off',
    'unicorn/prefer-event-target': 'off',
    'unicorn/no-thenable': 'off',
    'unicorn/import-style': 'off',
    'unicorn/prefer-structured-clone': 'off',
    '@typescript-eslint/await-thenable': 'error',
    '@typescript-eslint/no-misused-promises': 'error',
    'require-await': 'off',
    '@typescript-eslint/require-await': 'error',
    curly: 2,
    'prettier/prettier': 0,

    'no-restricted-imports':
      [
        'error',
        {
          patterns:
            [{ group: ['.*'], message: 'Relative imports are not allowed.' }]
        }
      ]
  }
