name: Create new release tag

on:
  workflow_dispatch:
    inputs:
      element:
        description: 'Version element to bump'
        required: true
        default: 'minor'
        type: choice
        options:
        - minor
        - patch

jobs:
  tag_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Script
        # TODO: Replace with call to #1398 script
        run: |
          CURRENT_SERVER=$(cat server/package.json | jq -r '.version')

          MAJOR=$(echo $CURRENT_SERVER | cut -d '.' -f1)
          MINOR=$(echo $CURRENT_SERVER | cut -d '.' -f2)
          PATCH=$(echo $CURRENT_SERVER | cut -d '.' -f3)

          if [[ ${{ inputs.element }} == "major" ]]; then
            $((MAJOR++))
          elif [[ ${{ inputs.element }} == "minor" ]]; then
            $((MINOR++))
          elif [[ ${{ inputs.element }} == "patch" ]]; then
            $((PATCH++))
          else
            echo 'Expected <major|minor|patch>'
            exit 1
          fi

          NEXT_SERVER=$MAJOR.$MINOR.$PATCH
          echo $NEXT_SERVER > new_version
          
      - name: Commit and tag
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Immich Release Bot
          author_email: bot@immich.app
          message: "Version $NEXT_SERVER"
          tag: $NEXT_SERVER
          push: true
          
      - name: Create new release
        run: echo "TODO"
